package com.b2w.starwarsapi.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Objects;

@DynamoDBTable(tableName = "star.wars.api.planeta")
public class Planeta {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String planetaId;

    @DynamoDBAttribute
    @NotBlank(message = "O nome do planeta deve ser informado")
    private String nome;

    @DynamoDBAttribute
    @NotBlank(message = "O clima do planeta deve ser informado")
    private String clima;

    @DynamoDBAttribute
    @NotBlank(message = "O terreno do planeta deve ser informado")
    private String terreno;

    public String getPlanetaId() {
        return planetaId;
    }

    public void setPlanetaId(String planetaId) {
        this.planetaId = planetaId;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getClima() {
        return clima;
    }

    public void setClima(String clima) {
        this.clima = clima;
    }

    public String getTerreno() {
        return terreno;
    }

    public void setTerreno(String terreno) {
        this.terreno = terreno;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Planeta planeta = (Planeta) o;
        return planetaId.equals(planeta.planetaId) && nome.equals(planeta.nome) && clima.equals(planeta.clima) && terreno.equals(planeta.terreno);
    }

    @Override
    public int hashCode() {
        return Objects.hash(planetaId, nome, clima, terreno);
    }
}
