package com.b2w.starwarsapi.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "star.wars.api.planeta")
public class Planeta {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String planetaId;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String clima;

    @DynamoDBAttribute
    private String terreno;

    @DynamoDBAttribute
    private String qtdAparicoes;

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getClima() {
        return clima;
    }

    public void setClima(String clima) {
        this.clima = clima;
    }

    public String getTerreno() {
        return terreno;
    }

    public void setTerreno(String terreno) {
        this.terreno = terreno;
    }

    public String getQtdAparicoes() {
        return qtdAparicoes;
    }

    public void setQtdAparicoes(String qtdAparicoes) {
        this.qtdAparicoes = qtdAparicoes;
    }
}
